CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE todo_status
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_done BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_todo_status PRIMARY KEY (id)
);

CREATE TABLE todo_priority
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    priority_type INTEGER,
    CONSTRAINT pk_todo_priority PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE user_status
(
    id     INTEGER NOT NULL,
    status VARCHAR(255),
    CONSTRAINT pk_user_status PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE account
(
    id            INTEGER NOT NULL,
    username      VARCHAR(255),
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    password      VARCHAR(255),
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    status_id     INTEGER,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE account
    ADD CONSTRAINT FK_USER_ON_STATUS FOREIGN KEY (status_id) REFERENCES user_status (id);

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE todo_item
(
    id            INTEGER NOT NULL,
    user_id       INTEGER,
    title         VARCHAR(255),
    details       VARCHAR(255),
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    priority_id   INTEGER,
    status_id     INTEGER,
    CONSTRAINT pk_todo_item PRIMARY KEY (id)
);

ALTER TABLE todo_item
    ADD CONSTRAINT FK_TODO_ITEM_ON_PRIORITY FOREIGN KEY (priority_id) REFERENCES todo_priority (id);

ALTER TABLE todo_item
    ADD CONSTRAINT FK_TODO_ITEM_ON_STATUS FOREIGN KEY (status_id) REFERENCES todo_status (id);

ALTER TABLE todo_item
    ADD CONSTRAINT FK_TODO_ITEM_ON_USER FOREIGN KEY (user_id) REFERENCES account (id);